docs/tables/oci_events_rule.md
<details>
```
```
</details>
<details>
```
> select
id as rule_id,
display_name,
condition ->> 'eventType' as event_type
from
oci_events_rule;
+----------------------------------------------------------------------------------------------+--------------------+---------------------------------------------------------------------------------------
| rule_id                                                                                      | display_name       | event_type                                                                            
+----------------------------------------------------------------------------------------------+--------------------+---------------------------------------- …
```
=> Remove the reference of connection name from example query in `oci_events_rule` document. Closes #103

docs/tables/oci_identity_compartment.md
<details>
```
```
</details>
<details>
```
> select
child.name as name,
coalesce(parent.name, 'root') as parent_compartment,
child.id as id,
coalesce(parent.id, child.tenant_id) as parent_compartment_id
from
oci_identity_compartment child
left join oci_identity_compartment parent on (child.compartment_id = parent.id)
order by
parent.name;
+---------------------------+---------------------+-------------------------------------------------------------------------------------+-------------------------------------------------------------------
| name                      | parent_compartment  | id                                                                                  | parent_compartment_id …
```
=> fix example query in oci_identity_compartment. Closes #133

oci/multi_region.go
<details>
```
```
</details>
<details>
```
> select * from oci_dns_zone
+------------+------------------------------------------------------+-----------------+-----------+---------------------+--------------+--------+--------+--------------------------------------------------
| name       | id                                                   | lifecycle_state | zone_type | time_created        | is_protected | scope  | serial | self                                             
+------------+------------------------------------------------------+-----------------+-----------+---------------------+--------------+--------+--------+--------------------------------------------------
| testqw.com | …
```
=> getting NotAuthorizedOrNotFound error in oci_dns_zone. Closes #150

docs/index.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Minor syntax correction. Closes #172

oci/table_oci_budget_budget.go
<details>
```
```
</details>
<details>
```
```
</details>
=> Fix oci_budget_budget

oci/table_oci_mysql_db_system.go
<details>
```
> select id, region from oci_mysql_db_system
+--------------------------------------------------------------------------------------------------+--------------+
| id                                                                                               | region       |
+--------------------------------------------------------------------------------------------------+--------------+
| ocid1.mysqldbsystem.oc1.ap-mumbai-1.aaaaaaaaeitr6ct3e6e6mbnxvknulfv3nymh62hooxkxe5uiku47iydplaqa | ap-mumbai-1  |
| ocid1.mysqldbsystem.oc1.ap-mumbai-1.aaaaaaaaefo3gszgcdibxx6ilrfa3zbezho6niqmljrpf5yiarfcvgpkcjja | ap-mumbai-1  |
| ocid1.mysqldbsystem.oc1.ap-mumbai-1.aaaaaaaaqnaysotrc2ek4wyiwjyptvib2fkgxsrms37qhzcomjvtktdjkv7q | ap-mumbai-1  |
| …
```
=> Add region column in oci_mysql_db_system. Closes #234

.github/workflows/golangci-lint.yml, oci/monitoring_metric.go, oci/multi_region.go, oci/table_oci_apigateway_api.go, oci/table_oci_autoscaling_auto_scaling_configuration.go, oci/table_oci_events_rule.go, oci/table_oci_file_storage_file_system.go, oci/table_oci_functions_application.go, oci/table_oci_kms_vault.go, oci/table_oci_logging_log.go, oci/table_oci_logging_log_group.go, oci/table_oci_mysql_backup.go, oci/table_oci_mysql_channel.go, oci/table_oci_mysql_db_system.go, oci/table_oci_ons_notification_topic.go, oci/table_oci_ons_subscription.go
<details>
```
```
</details>
<details>
```
```
</details>
=> Add golangci-lint work flow and fix suggestions. Closes #267

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.3.0 closes #304

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.3.1 closes #310

oci/service.go, oci/table_oci_apigateway_api.go
<details>
```
arnab@turbotindias-MacBook-Pro oci-test % ./tint.js oci_apigateway_api
Test names: [ 'tests/oci_apigateway_api' ]
SETUP: tests/oci_apigateway_api []
PRETEST: tests/oci_apigateway_api
TEST: tests/oci_apigateway_api
oci_apigateway_api.named_test_resource: Refreshing state... [id=ocid1.apigatewayapi.oc1.ap-mumbai-1.amaaaaaa6igdexaae5b7yjpxgscqj4hswwpgijf5mvmb4jue6bnh2hhfspza]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":
- resource "oci_apigateway_api" "named_test_resource" {
- compartment_id …
```
=> Fix list request in table oci_apigateway_api. Closes #321

.github/workflows/registry-publish.yml, go.mod
<details>
```
> select * from oci_budget_budget
+------------------------------------+--------------------------------------------------------------------------------+--------+-------------------+-----------------+--------------------------------------
| display_name                       | id                                                                             | amount | actual_spend      | lifecycle_state | target_compartment_id                
+------------------------------------+--------------------------------------------------------------------------------+--------+-------------------+-----------------+--------------------------------------
| raj-sp-query-dev-child-compartment | ocid1.budget.oc1..aaaaaaaamzhubsdjhs222c4x4knjultoeiao5hxedv6667uasqjzy …
```
=> Update go version to 1.17

go.mod, go.sum
<details>
```
```
</details>
<details>
```
select
name,
namespace,
storage_tier,
is_read_only
from
oci_objectstorage_bucket;
+----------------------------------------------------------------------------------------------------+--------------+--------------+--------------+
| name                                                                                               | namespace    | storage_tier | is_read_only |
+----------------------------------------------------------------------------------------------------+--------------+--------------+--------------+
| bucket-20210809-1006                                                                               | bmqeqvslavsz | Standard     | false …
```
=> Recompile plugin with steampipe-plugin-sdk v2.1.1

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Update latest Steampipe plugin SDK hyperlink in the CHANGELOG

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.17.2

oci/table_oci_core_volume_backup_policy.go
<details>
```
> select * from oci_core_volume_backup_policy where id = 'ocid1.volumebackuppolicy.oc1.ap-mumbai-1.amaaaaaa6igdexaaqt5j7jsuoooibrqdicpqk7numkevyszxp2n3573xbvaq'
+-----------------------------+-------------------------------------------------------------------------------------------------------+---------------------------+--------------------+-----------+--------------+---
| display_name                | id                                                                                                    | time_created              | destination_region | schedules | defined_tags | fr
+-----------------------------+-------------------------------------------------------------------------------------------------------+---------------------------+----- …
```
=> Fix region issue in get call in oci_core_volume_backup_policy table

oci/table_oci_file_storage_file_system.go
<details>
```
Test names: [ 'tests/oci_file_storage_file_system' ]
SETUP: tests/oci_file_storage_file_system []
PRETEST: tests/oci_file_storage_file_system
TEST: tests/oci_file_storage_file_system
+ create
+ resource "oci_file_storage_file_system" "named_test_resource" {
+ availability_domain   = "TvRS:AP-MUMBAI-1-AD-1"
+ compartment_id        = "ocid1.compartment.oc1..aaaaaaaapohc2vvmuywosa6ltfxrx2mhhcjfmvqexdqfhkahfweiwe33 …
```
=> Update getFileStorageFileSystemExports function in table oci_file_storage_file_system specifically. Fixes #465

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.19.1

docs/tables/oci_bastion_bastion.md, docs/tables/oci_bastion_session.md, oci/plugin.go, oci/service.go, oci/table_oci_bastion_bastion.go, oci/table_oci_bastion_session.go
Co-authored-by: Scott Fletcher <scott.fletcher@oracle.com>
Co-authored-by: Ved misra <47312748+misraved@users.noreply.github.com>
This PR includes the following tables:
- oci_bastion_bastion
- oci_bastion_session
<details>
```
```
</details>
<details>
```
```
</details>
=> Add bastion tables (#435)

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.20.0

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.21.0

oci/table_oci_identity_policy.go
<details>
```
```
</details>
<details>
```
> select
name,
id,
description,
tenant_id
from
oci_identity_policy 
order by 
time_created desc 
limit 5;
+-----------------------------+--------------------------------------------------------------------------------+-----------------------------+-------------------------------------------------------------------------------------+
| name                        | id                                                                             | description                 | tenant_id                                                                           |
+-----------------------------+------------------------------------------------------------------------ …
```
=> Fix `oci_identity_policy` table only returns policy for the root compartment. Closes #470

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.28.0

docs/tables/oci_container_instances_container.md, oci/plugin.go, oci/table_oci_container_instances_container.go, oci/table_oci_container_instances_container_container.go
<details>
```
N/A
```
</details>
<details>
```sql
> select
display_name,
id,
availability_domain,
time_created,
image_url
from
oci_container_instances_container;
+---------------------------+---------------------------------------------------------------------------------------------+----------------------+-----------------+-----------------------
| display_name              | id                                                                                          | availability_domain  | lifecycle_state | time_created          
+---------------------------+---------------------------------------------------------------------------------------------+----------------------+-----------------+-----------------------
| …
```
=> Add table oci_container_instances_container

docs/tables/oci_container_instances_container.md, docs/tables/oci_container_instances_container_instance.md, oci/plugin.go, oci/service.go, oci/table_oci_container_instances_container.go, oci/table_oci_container_instances_container_instance.go
<details>
```
N/A
```
</details>
<details>
```sql
select
display_name,
id,
availability_domain,
time_created,
container_count
from
oci_container_instances_container_instance;
+----------------------------------+-----------------------------------------------------------------------------------------------------+----------------------+-----------------+--------
| display_name                     | id                                                                                                  | availability_domain  | lifecycle_state | time_cr
+----------------------------------+-----------------------------------------------------------------------------------------------------+----------------------+-----------------+-- …
```
=> Add table oci_container_instances_container_instance

oci/multi_region.go
<details>
```
```
</details>
<details>
```
```
</details>
=> Update getInvalidRegions method to always check regions from updated region list of OCI.

oci/multi_region.go
<details>
```
```
</details>
<details>
```
```
</details>
=> Fix index out of range error when regions config arg is not set 

oci/table_oci_identity_user.go
<details>
```
```
</details>
<details>
```sql
select name, time_created, last_successful_login_time, lifecycle_state from oci_identity_user where name = 'madhushreeray30'
+-----------------+---------------------------+----------------------------+-----------------+
| name            | time_created              | last_successful_login_time | lifecycle_state |
+-----------------+---------------------------+----------------------------+-----------------+
| madhushreeray30 | 2022-11-10T17:01:00+05:30 | 2023-09-25T09:34:26+05:30  | ACTIVE          |
+-----------------+---------------------------+----------------------------+-----------------+
```
</details>
=> Add column `last_successful_login_time` to `oci_identity_user` table. Closes #546.

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v0.32.1

docs/tables/oci_database_cloud_vm_cluster.md, oci/plugin.go, oci/table_oci_database_cloud_vm_cluster.go
<details>
```
N/A
```
</details>
<details>
```
N/A
```
</details>
=> Add table oci_database_cloud_vm_cluster Closes #571

docs/tables/oci_database_exadata_infrastructure.md, oci/plugin.go, oci/table_oci_database_exadata_infrastructure.go
<details>
```
N/A 
```
</details>
<details>
```
N/A
```
</details>
=> Add table oci_database_exadata_infrastructure Closes #570

oci-test/tint.js
<details>
```
```
</details>
<details>
```
```
</details>
=> Fixed the integration test script as per the latest Steampipe CLI result

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Update CHANGELOG for v0.36.0

CHANGELOG.md
<details>
```
```
</details>
<details>
```
```
</details>
=> Add CHANGELOG for v1.0.1
