docs/tables/oci_cloud_guard_detector_recipe.md
docs/tables/oci_cloud_guard_managed_list.md
docs/tables/oci_cloud_guard_responder_recipe.md
oci/common_columns.go
oci/table_oci_cloud_guard_detector_recipe.go
oci/table_oci_cloud_guard_managed_list.go
oci/table_oci_cloud_guard_responder_recipe.go

<details>
```
SETUP: tests/oci_cloud_guard_detector_recipe []
PRETEST: tests/oci_cloud_guard_detector_recipe
TEST: tests/oci_cloud_guard_detector_recipe
oci_cloud_guard_detector_recipe.named_test_resource: Creating...
oci_cloud_guard_detector_recipe.named_test_resource: Creation complete after 2s [id=ocid1.cloudguarddetectorrecipe.oc1.ap-mumbai-1.amaaaaaa6igdexaauolphxgsujftpaqikzephakqwulwymlll5zqxn5gpgaa]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Outputs:
resource_id = "ocid1.cloudguarddetectorrecipe.oc1.ap-mumbai-1.amaaaaaa6igdexaauolphxgsujftpaqikzephakqwulwymlll5zqxn5gpgaa"
resource_name = "steampipetest804"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
Running SQL query: …
```

Hydrate columns values did not populate in cloudguard tables in list call. Closes #123

---

oci/table_oci_dns_tsig_key.go

<details>
```
```
</details>
<details>
```
> select name,id,lifecycle_state,self from oci_dns_tsig_key
+-----------+----------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------
| name      | id                                                       | lifecycle_state | self                                                                                                             
+-----------+----------------------------------------------------------+-----------------+----------------------------------------------------------------------------------------------------------- …
```

remove region column from oci_dns_tsig_key. Closes#158

---

oci/table_oci_dns_zone.go

<details>
```
```
</details>
<details>
```
> select name,id,lifecycle_state,self from oci_dns_zone
+------------+------------------------------------------------------+-----------------+--------------------------------------------------------------------+
| name       | id                                                   | lifecycle_state | self                                                               |
+------------+------------------------------------------------------+-----------------+--------------------------------------------------------------------+
| testqw.com | ocid1.dns-zone.oc1..21bbfca7cd0f48dea250a44f3282d7cf | ACTIVE          | …
```

Remove region column from oci_dns_zone. Closes #156

---

docs/tables/oci_kms_key_version.md

<details>
```
```
<details>
```
> select
k.name as key_name,
k.lifecycle_state,
k.region,
max(v.time_created) as latest_key_version_created
from
oci_kms_key k,
oci_kms_key_version v
where
v.key_id = k.id
and v.management_endpoint = k.management_endpoint
and v.region = k.region
and k.lifecycle_state = 'ENABLED'
group by
key_name, k.lifecycle_state, k.region
+------------------------------------+-----------------+--------------+----------------------------+
| key_name                           | lifecycle_state | region       | latest_key_version_created |
+------------------------------------+-----------------+--------------+----------------------------+
| software-cmk-raj                   | ENABLED         | ap-mumbai-1  | 2021-06-28 …
```

Updated  oci_kms_key_version doc example query.Closes #153

---

docs/tables/oci_objectstorage_bucket.md
oci-test/tests/oci_objectstorage_bucket/test-hydrate-expected.json
oci-test/tests/oci_objectstorage_bucket/test-hydrate-query.sql
oci-test/tests/oci_objectstorage_bucket/variables.tf
oci/table_oci_objectstorage_bucket.go

<details>
```
Test names: [ 'tests/oci_objectstorage_bucket' ]
Custom env variable TURBOT_TEST_EXPECTED_TIMEOUT=300
SETUP: tests/oci_objectstorage_bucket []
PRETEST: tests/oci_objectstorage_bucket
TEST: tests/oci_objectstorage_bucket
data.oci_objectstorage_namespace.test_namespace: Refreshing state...
oci_objectstorage_bucket.named_test_resource: Creating...
oci_objectstorage_bucket.named_test_resource: Creation complete after 0s [id=n/bmqeqvslavsz/b/steampipetest5489]
oci_objectstorage_object_lifecycle_policy.test_object_lifecycle_policy: Creating... …
```

Add column object_lifecycle_policy in the table oci_objectstorage_bucket. Closes #186

---

oci/service.go

<details>
```
N/A
```
</details>
<details>
```
N/A
```
</details>

Fix error: undeclared tenantID when defining service connection for networkLoadBalancerService. Closes #231

---

oci/monitoring_metric.go
oci/table_oci_core_boot_volume_metric_read_ops.go
oci/table_oci_core_boot_volume_metric_read_ops_daily.go
oci/table_oci_core_boot_volume_metric_read_ops_hourly.go
oci/table_oci_core_boot_volume_metric_write_ops.go
oci/table_oci_core_boot_volume_metric_write_ops_daily.go
oci/table_oci_core_boot_volume_metric_write_ops_hourly.go
oci/table_oci_core_instance_metric_cpu_utilization.go
oci/table_oci_core_instance_metric_cpu_utilization_daily.go
oci/table_oci_core_instance_metric_cpu_utilization_hourly.go
oci/table_oci_nosql_table_metric_read_throttle_count.go
oci/table_oci_nosql_table_metric_read_throttle_count_daily.go
oci/table_oci_nosql_table_metric_read_throttle_count_hourly.go
oci/table_oci_nosql_table_metric_storage_utilization.go
oci/table_oci_nosql_table_metric_storage_utilization_daily.go
oci/table_oci_nosql_table_metric_storage_utilization_hourly.go
oci/table_oci_nosql_table_metric_write_throttle_count.go
oci/table_oci_nosql_table_metric_write_throttle_count_daily.go
oci/table_oci_nosql_table_metric_write_throttle_count_hourly.go

<details>
```
```
</details>
<details>
```
> with core_instance_utilization as (
select
id,
round(cast(sum(maximum)/count(maximum) as numeric), 1) as avg_max,
count(maximum) days
from
oci_core_instance_metric_cpu_utilization_daily
where
date_part('day', now() - timestamp) <=30
group by
id
)
select
i.id as resource,
case
when avg_max is null then 'error'
when avg_max < 20 then 'alarm'
when avg_max < 35 then 'info'
else 'ok'
end as status,
case
when avg_max is null then 'Metrics not available for ' || i.title || '.'
else i.title || ' is averaging ' || avg_max || '% max utilization over the last ' || days || ' days.'
end as reason,
i.region,
coalesce(c.name, 'root') as compartment
from
oci_core_instance …
```

Add Column region for metric tables. Closes #239

---

oci/monitoring_metric.go
oci/service.go

Metric statistics should show the details for resource available in multiple regions
SPC file: 
```
regions   = ["us-ashburn-1","ap-mumbai-1","ap-hyderabad-1"]
```
Output: 
```
> select * from oci_core_boot_volume_metric_read_ops_daily
+--------------------------------------------------------------------------------------------------+---------------+----------------+---------------------+---------+---------+--------------+-------+------
| id                                                                                               | metric_name   | namespace      | average             | maximum | minimum | sample_count | sum   | unit 
+--------------------------------------------------------------------------------------------------+---------------+----------------+--------------------- …
```

Metric statistic table should show data of multiple regions closes #242

---

oci-test/tests/oci_file_storage_file_system/test-turbot-expected.json
oci/table_oci_core_block_volume_replica.go
oci/table_oci_core_boot_volume.go
oci/table_oci_core_boot_volume_attachment.go
oci/table_oci_core_boot_volume_replica.go
oci/table_oci_file_storage_file_system.go
oci/table_oci_file_storage_snapshot.go

<details>
```
SETUP: tests/oci_file_storage_file_system []
PRETEST: tests/oci_file_storage_file_system
TEST: tests/oci_file_storage_file_system
oci_file_storage_file_system.named_test_resource: Creating...
oci_file_storage_file_system.named_test_resource: Creation complete after 4s [id=ocid1.filesystem.oc1.iad.aaaaaaaaaaa4haronfqwillqojxwiotjmfsc2ylefuzqaaaa]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Outputs:
availability_domain = "TvRS:US-ASHBURN-AD-1"
freeform_tags = tomap({
"Name" = "steampipetest5807"
})
region = "us-ashburn-1"
resource_id = "ocid1.filesystem.oc1.iad.aaaaaaaaaaa4haronfqwillqojxwiotjmfsc2ylefuzqaaaa"
resource_name = "steampipetest5807"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4p …
```

Fix get call issue in tables where we are using zone from GetMatrixItem. Closes #262

---

docs/tables/oci_core_image.md
oci-test/tests/oci_core_image/test-get-expected.json
oci-test/tests/oci_core_image/test-get-query.sql
oci-test/tests/oci_core_image/test-list-expected.json
oci-test/tests/oci_core_image/test-list-query.sql
oci-test/tests/oci_core_image/test-turbot-expected.json
oci-test/tests/oci_core_image/variables.tf
oci/table_oci_core_image.go

<details>
```
SETUP: tests/oci_core_image []
PRETEST: tests/oci_core_image
TEST: tests/oci_core_image
null_resource.named_test_resource: Creating...
null_resource.named_test_resource: Provisioning with 'local-exec'...
null_resource.named_test_resource (local-exec): Executing: ["/bin/sh" "-c" "oci compute image list --compartment-id ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq --region ap-mumbai-1 --output json > /private/var/folders/d8/gsp6f_cn3359xnt_gs3cts_80000gn/T/tests/oci_core_image/terraform/test/output.json"]
null_resource.named_test_resource (local-exec): WARNING: Permissions on /Users/sourav/-04-08-07-40.pem are too open.
null_resource.named_test_resource (local-exec): To fix this please try executing …
```

Update oci_core_image table to list only platform(standard) images. Closes #212

---

oci-test/tests/oci_cloud_guard_configuration/test-list-expected.json
oci-test/tests/oci_cloud_guard_configuration/test-list-query.sql
oci-test/tests/oci_cloud_guard_configuration/test-not-found-query.sql
oci-test/tests/oci_cloud_guard_configuration/test-turbot-query.sql
oci-test/tests/oci_cloud_guard_configuration/variables.tf

<details>
```
arnab@turbotindias-MacBook-Pro oci-test % ./tint.js oci_cloud_guard_configuration
Test names: [ 'tests/oci_cloud_guard_configuration' ]
SETUP: tests/oci_cloud_guard_configuration []
PRETEST: tests/oci_cloud_guard_configuration
TEST: tests/oci_cloud_guard_configuration
+ create
<= read (data resources)
<= data "local_file" "input"  {
+ content        = (known after apply)
+ content_base64 = (known after apply) …
```

Fix integration tests for table oci_cloud_guard_configuration. Closes #322

---

docs/tables/oci_logging_log_group.md
oci/table_oci_core_nat_gateway.go
oci/table_oci_logging_log_group.go

<details>
```
arnab@turbotindias-MacBook-Pro oci-test % ./tint.js oci_logging_log_group
Test names: [ 'tests/oci_logging_log_group' ]
SETUP: tests/oci_logging_log_group []
PRETEST: tests/oci_logging_log_group
TEST: tests/oci_logging_log_group
+ create
+ resource "oci_logging_log_group" "test_log_group" {
+ compartment_id     = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
+ defined_tags …
```

Handle 'InvalidParameter', '400' and '404' errors in table_oci_logging_log_group and table_oci_core_nat_gateway. Closes #326

---

oci-test/tests/oci_cloud_guard_detector_recipe/variables.tf
oci-test/tests/oci_cloud_guard_responder_recipe/variables.tf
oci/multi_region.go
oci/service.go
oci/table_oci_cloud_guard_configuration.go
oci/table_oci_cloud_guard_detector_recipe.go
oci/table_oci_cloud_guard_managed_list.go
oci/table_oci_cloud_guard_responder_recipe.go
oci/table_oci_cloud_guard_target.go

<details>
```
SETUP: tests/oci_cloud_guard_configuration []
PRETEST: tests/oci_cloud_guard_configuration
TEST: tests/oci_cloud_guard_configuration
+ create
<= read (data resources)
<= data "local_file" "input"  {
+ content        = (known after apply)
+ content_base64 = (known after apply)
+ filename       = "/private/var/folders/3j/6ybdbkm51c3449psm55pjsg00000gp/T/tests/oci_cloud_guard_configuration/terraform/test/output.json"
+ id             = (known after apply)
}
+ resource "null_resource" "named_test_resource" {
+ id = (known after apply)
}
Plan: 1 to add, 0 …
```

Added reporting region in service for CloudGuard tables.

---

docs/tables/oci_functions_function.md
oci/plugin.go
oci/table_oci_functions_function.go

**Integration test is not feasible**
<details>
```
> select
display_name,
id,
application_id,
image,
image_digest
from
oci_functions_function;
+--------------+-----------------------------------------------------------------------------------+----------------------------------------------------------------------------------+-----------------+------------------------------------------------+-------------------------------------------------------------------------+
| display_name | id                                                                                | application_id                                                                   | lifecycle_state | image                                          | image_digest …
```

Add table oci_functions_function

---

docs/tables/oci_objectstorage_object.md
oci/plugin.go
oci/table_oci_objectstorage_object.go

**Tests not feasible**
<details>
```
> select
name,
bucket_name,
namespace,
region,
size,
md5,
time_created,
time_modified
from
oci_objectstorage_object;
+-------------------------+----------------------+--------------+--------------+--------+--------------------------+---------------------------+---------------------------+
| name                    | bucket_name          | namespace    | region       | size   | md5                      | time_created              | time_modified             |
+-------------------------+----------------------+--------------+--------------+--------+--------------------------+---------------------------+---------------------------+
| test-obj-1object.txt    | test-buket           | bmqeqvslavsz | ap-mumbai-1  | 517    | …
```

Add table oci_objectstorage_object. Closes #338

---

oci/table_oci_objectstorage_bucket.go

<details>
```
> select name, time_created from oci_objectstorage_bucket
+----------------------+---------------------------+
| name                 | time_created              |
+----------------------+---------------------------+
| bucket-20210809-1006 | 2021-08-09T19:35:03+05:30 |
| test-buket           | 2022-01-06T14:16:59+05:30 |
| test-bucket-archive  | 2022-01-12T12:37:34+05:30 |
| test-buket           | 2022-01-06T14:23:01+05:30 |
+----------------------+---------------------------+
```
</details>

Update column type for column time_created to TIMESTAMP in oci_objectstorage_bucket table. Fixes #347

---

docs/tables/oci_mysql_db_system_metric_cpu_utilization_hourly.md
oci/plugin.go
oci/table_oci_mysql_db_system_metric_cpu_utilization_hourly.go

<details>
```
N/A
```
</details>
<details>
```
> select
id,
timestamp,
minimum,
maximum,
average,
sample_count
from
oci_mysql_db_system_metric_cpu_utilization_hourly
order by
id,
timestamp;
+------------------------------------------------------------------------------------------+---------------------------+---------+---------+--------------------+--------------+
| id                                                                                       | timestamp                 | minimum | maximum | average            | sample_count |
+------------------------------------------------------------------------------------------+---------------------------+---------+---------+--------------------+--------------+
| …
```

Add table oci_mysql_db_system_metric_cpu_utilization_hourly closes #351

---

docs/tables/oci_database_autonomous_database_metric_cpu_utilization_hourly.md
oci/plugin.go
oci/table_oci_database_autonomous_database_cpu_utilization_hourly.go

<details>
```
N/A
```
</details>
<details>
```
> select * from oci_database_autonomous_database_metric_cpu_utilization_hourly
+-----------------------------------------------------------------------------------------------+----------------+-------------------------+--------------------+--------------------+-------------------+--
| id                                                                                            | metric_name    | namespace               | average            | maximum            | minimum           | s
+-----------------------------------------------------------------------------------------------+----------------+-------------------------+--------------------+--------------------+-------------------+--
| …
```

Add table oci_database_autonomous_database_metric_cpu_utilization_hourly closes #350

---

oci/table_oci_dns_rrset.go

<details>
```
Test names: [ 'tests/oci_dns_rrset' ]
SETUP: tests/oci_dns_rrset []
PRETEST: tests/oci_dns_rrset
TEST: tests/oci_dns_rrset
oci_dns_zone.named_test_resource: Creating...
oci_dns_zone.named_test_resource: Still creating... [10s elapsed]
oci_dns_zone.named_test_resource: Still creating... [20s elapsed]
oci_dns_zone.named_test_resource: Creation complete after 28s [id=ocid1.dns-zone.oc1..f86ed5f4e4614b399bfeccd42e9975f7]
oci_dns_rrset.named_test_resource: Creating...
oci_dns_rrset.named_test_resource: Still creating... [10s elapsed]
oci_dns_rrset.named_test_resource: Creation complete after 17s …
```

Fix table oci_dns_rrset for error InvalidParameter in list call closes #356

---

oci/table_oci_kms_key.go

<details>
```
> select
id,
name,
time_created,
vault_name
from
oci_kms_key;
+------------------------------------------------------------------------------------------------------+---------------------+------------------+---------------------------+-------------------+
| id                                                                                                   | name                | lifecycle_state  | time_created              | vault_name        |
+------------------------------------------------------------------------------------------------------+---------------------+------------------+---------------------------+-------------------+
| ocid1.key.oc1.ap-mumbai-1.cvrbl7hpaabz4.abrg6ljr3cu2wcauwcpu5ub5byakswdckgs6i5ji6mu465ycfd7esmaw …
```

Fixed oci_kms_key table to list all keys from different compartment other than vault's compartment only. Fixes #361

---

oci/table_oci_core_vnic_attachment.go

<details>
```
> .inspect oci_core_vnic_attachment
+------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| column                 | type                     | description                                                                                                                                        |
+------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| _ctx                   | jsonb                    | Steampipe context in JSON form, e.g. connection_name. …
```

Fix column name lifecycle_state in oci_core_vnic_attachment table closes #367

---

oci/table_oci_core_boot_volume.go
oci/table_oci_core_volume.go

<details>
```
> select display_name, volume_backup_policy_id, volume_backup_policy_assignment_id  from oci_core_boot_volume
+--------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------------------
| display_name                         | volume_backup_policy_id                                                                    | volume_backup_policy_assignment_id                                    
+--------------------------------------+--------------------------------------------------------------------------------------------+-----------------------------------------------------------------------
| instance-20220307-1153 (Boot …
```

Add column volume_backup_policy_id and volume_backup_policy_assignment_id in oci_core_boot_volume and oci_core_volume table

---

docs/tables/oci_mysql_db_system_metric_connections_hourly.md
oci/plugin.go
oci/table_oci_mysql_db_system_metric_connections_hourly.go

<details>
```
```
</details>
<details>
```
> select
id,
timestamp,
round(minimum::numeric,2) as min_conn,
round(maximum::numeric,2) as max_conn,
round(average::numeric,2) as avg_conn,
sample_count
from
oci_mysql_db_system_metric_connections_hourly
where metric_name = 'CurrentConnections'
order by
id,
timestamp limit 3;
+--------------------------------------------------------------------------------------------------+---------------------------+----------+----------+----------+--------------+
| id                                                                                               | timestamp                 | min_conn | max_conn | avg_conn | sample_count | …
```

Added table oci_mysql_db_system_metric_connections_hourly. Closes #379

---

oci/table_oci_core_vcn.go

<details>
```
> select display_name,ipv6_cidr_blocks from oci_core_vcn
+-------------------+------------------------------+
| display_name      | ipv6_cidr_blocks             |
+-------------------+------------------------------+
| vcn-20220222-1132 | <null>                       |
| vcn-20220208-1530 | ["2603:c021:4000:e000::/56"] |
| vcn-20220209-1247 | <null>                       |
+-------------------+------------------------------+
```
</details>

Add column ipv6_cidr_blocks in oci_core_vcn table. Closes #389

---

CHANGELOG.md
docs/tables/oci_database_pluggable_database.md
oci/plugin.go
oci/table_oci_database_pluggable_database.go

<details>
```
TF resource creation for the parent resource DB system has issues, also CLI is not feasible.
```
</details>
<details>
```
> select
pdb_name,
id,
time_created
from
oci_database_pluggable_database
+-------------+------------------------------------------------------------------------------------------------------+-----------------+---------------------------+
| pdb_name    | id                                                                                                   | lifecycle_state | time_created              |
+-------------+------------------------------------------------------------------------------------------------------+-----------------+---------------------------+
| DB0324_pdb1 | …
```

Add table oci_database_pluggable_database. Closes #290

---

oci/plugin.go

<details>
```
N/A
```
</details>
<details>
```
> select * from oci_database_autonomous_db_metric_storage_utilization
+-------------------------------------------------------------------------------------------------------+--------------------+-------------------------+--------------------+--------------------+----------
| id                                                                                                    | metric_name        | namespace               | average            | maximum            | minimum  
+-------------------------------------------------------------------------------------------------------+--------------------+-------------------------+--------------------+--------------------+----------
| …
```

Rename table oci_database_autonomous_dd_metric_storage_utilization to oci_database_autonomous_db_metric_storage_utilization closes #416

---

docs/tables/oci_identity_compartment.md

OCI supports compartments in compartments, like a folder structure. This example show how to do a full path compartment listing.

Added example of how to do full path compartment listing.

---

oci/table_oci_file_storage_file_system.go

<details>
```
Test names: [ 'tests/oci_file_storage_file_system' ]
SETUP: tests/oci_file_storage_file_system []
PRETEST: tests/oci_file_storage_file_system
TEST: tests/oci_file_storage_file_system
oci_file_storage_file_system.named_test_resource: Creating...
oci_file_storage_file_system.named_test_resource: Creation complete after 3s [id=ocid1.filesystem.oc1.ap_mumbai_1.aaaaaaaaaaaa5wdcmjxw2llqojxwiotboaww25lnmjqwsljrfvqwiljr]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Outputs:
availability_domain = TvRS:AP-MUMBAI-1-AD-1
freeform_tags = {
"Name" = "steampipetest3613"
}
region = …
```

Add exports details in table oci_file_storage_file_system closes #448

---

docs/tables/oci_identity_compartment.md

<details>
```
```
</details>
<details>
```
```
</details>

Fix the formatting of an example query in oci_identity_compartment table doc

---

docs/tables/oci_core_volume_default_backup_policy.md
oci/plugin.go
oci/table_oci_core_volume_default_backup_policy.go

<details>
```
N/A
```
</details>
<details>
```
> select
id,
display_name,
time_created,
region,
tags
from
oci_core_volume_default_backup_policy;
+--------------------------------------------------------------------------------------------+--------------+---------------------------+--------+------+
| id                                                                                         | display_name | time_created              | region | tags |
+--------------------------------------------------------------------------------------------+--------------+---------------------------+--------+------+
| ocid1.volumebackuppolicy.oc1..aaaaaaaa7hwv7iscewqqcmyqe2zuzfce6setvckhbxduswtxf6ctew7e54ja | silver       | 2017-10-01T05:30:00+05:30 | …
```

Add table oci_core_volume_default_backup_policy closes #462

---

docs/tables/oci_database_autonomous_database.md
oci/table_oci_database_autonomous_database.go

<details>
```
Test names: [ 'tests/oci_database_autonomous_database' ]
SETUP: tests/oci_database_autonomous_database []
PRETEST: tests/oci_database_autonomous_database
TEST: tests/oci_database_autonomous_database
+ create
+ resource "oci_database_autonomous_database" "named_test_resource" {
+ actual_used_data_storage_size_in_tbs           = (known after apply)
+ admin_password                                 = (sensitive …
```

Add KmsKeyId, VaultId ,KmsKeyVersionId column in table oci_database_autonomous_database closes #468

---

oci/table_oci_core_volume_backup_policy.go

<details>
```
Test names: [ 'tests/oci_core_volume_backup_policy' ]
SETUP: tests/oci_core_volume_backup_policy []
PRETEST: tests/oci_core_volume_backup_policy
TEST: tests/oci_core_volume_backup_policy
+ create
+ resource "oci_core_volume_backup_policy" "named_test_resource" {
+ compartment_id     = "ocid1.tenancy.oc1.fghsfghdasihinm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4p4h2q37cyljaq"
+ defined_tags       = (known after apply) …
```

Handle region check in get call in the table oci_core_volume_backup_policy closes #459

---

docs/tables/oci_core_cluster_network.md
oci/plugin.go
oci/service.go
oci/table_oci_core_cluster_network.go

<details>
```
N/A
```
</details>
<details>
```
> select * from oci_core_cluster_network
+---------------------------------------------------------------------------------------------------+-------------------------------+-----------------+---------------------------+---------------------------+---------------------------------------------------------------
| id                                                                                                | display_name                  | lifecycle_state | time_created              | time_updated              | instance_pools                                                
+---------------------------------------------------------------------------------------------------+------------------ …
```

Add table oci_core_cluster_network closes #449

---

oci/table_oci_core_cluster_network.go

```
> select * from oci_core_cluster_network where id = 'ocid1.clusternetwork.oc1.iad.amaaaaaa6igdexaayu2bq7n4rrcplupo6gbb3ly2qtlrykhxl3lzpctsfi4a'
+-------------------------------------------------------------------------------------------+-------------------------------+-----------------+---------------------------+---------------------------+---------------
| id                                                                                        | display_name                  | lifecycle_state | time_created              | time_updated              | instance_pools
+-------------------------------------------------------------------------------------------+-------------------------------+-----------------+---------------------------+---------------------------+---------------
| …
```

Fix region issue in get call in oci_core_cluster_network table

---

docs/tables/oci_queue_queue.md
oci/table_oci_queue_queue.go

<details>
```
```
</details>
<details>
```
```
</details>

Fix typo and formatting of log messages in oci_queue_queue table

---

docs/tables/oci_network_firewall_firewall.md
docs/tables/oci_network_firewall_policy.md
oci/plugin.go
oci/service.go
oci/table_oci_network_firewall_firewall.go
oci/table_oci_network_firewall_policy.go

<details>
```
```
</details>
<details>
```sql
select
id,
display_name,
availability_domain,
ipv4_address,
ipv6_address,
network_firewall_policy_id,
network_security_group_ids,
subnet_id,
lifecycle_state as state
from
oci_network_firewall_firewall;
[
{
"availability_domain": "TvRS:AP-MUMBAI-1-AD-1",
"display_name": "firewall-20230602-2053",
"id": "ocid1.networkfirewall.oc1.ap-mumbai-1.amaaaaaa6igdexaatb5ygqgxu21111162ysfgn7fmkymftyluq4eukhhm6uq",
"ipv4_address": "10.0.115.118",
"ipv6_address": null,
"network_firewall_policy_id": "ocid1.networkfirewallpolicy.oc1.ap-mumbai-1.amaaaaaa6igdexaaykejpv4rnrufcyb6w5awfb11111ms6quturswqcenvoa",
"network_security_group_ids": [],
"state": "CREATING",
"subnet_id": …
```

Add oci_network_firewall_firewall and oci_network_firewall_policy tables

---

oci/table_oci_identity_policy.go

<details>
```
```
</details>
<details>
```sql
> select * from oci_identity_policy limit 1
[
{
"_ctx": {
"connection_name": "oci"
},
"compartment_id": "ocid1.compartment.oc1..aaaaaaaaou2yc2w1111111111z6hhdo2ptcnzf6pfcmdrzlsodpccp5bux6a",
"defined_tags": {},
"description": "PSM managed compartment policy",
"freeform_tags": {},
"id": "ocid1.policy.oc1..aaaaaaaagufswrqktxc31111111111xkdfryhpxxxfihkyrps52tlklyb6qa",
"inactive_status": null,
"lifecycle_state": "ACTIVE",
"name": "PSM-mgd-comp-policy",
"statements": [
"allow any-user to read all-resources in compartment managedcompartmentforpaas",
"allow service PSM to manage all-resources in compartment managedcompartmentforpaas",
"allow any-user to manage …
```

Add column `compartment_id` in table `oci_identity_policy`

---

oci/table_oci_database_db.go

<details>
```
```
</details>
<details>
```
```
</details>

Added columns kms_key_version_id , vault_id, sid_prefix, is_cdb and database_management_config to the oci_database_db table. Closes #589

---

oci/utils.go

Allows for determining the object storage namespace of a foreign tenant in a cross-tenant query scenario
<details>
```
```
</details>
<details>
```
```
</details>

Add CompartmentId to GetNamespaceRequest
